### ISSUE TITLE
support revert insert sql contains database generated primary key  

### ISSUE THREAD

**Issue by cherrylzhao** [OpenSharding/shardingsphere-spi-impl#44]
currently，we only support revert sql contains primary key generated by shardingsphere or existing in values. we can get database generateKey after physical statement have completed.

**Comment by lvye351** [comment]
can you show the current status of this issue,no docs found!
we can get database generateKey after physical statement have completed
->it has been realized？

**Comment by cherrylzhao** [comment]
thanks for attention, we don't plan to implement it recently
