### ISSUE TITLE
这个项目如何编译啊，写个redme啊？？

### ISSUE THREAD

**Issue by Joe192168** [OpenSharding/shardingsphere-spi-impl#49]
好多pom架包下载不下来，毫无头绪。。。。

**Comment by Joe192168** [comment]
sharding-jdbc-core中央仓库只有4.0.0-RC1，而源码是${project.version}指的是当前项目版本4.0.0-RC2-SNAPSHOT，根本拉取不了。

**Comment by cherrylzhao** [comment]
for English only.
please switch to 4.0.0-RC1 tag. or you should `mvn clean install` dev branch of ShardingSphere code.
