### ISSUE TITLE
compile error 

### ISSUE THREAD

**Issue by taojintianxia** [OpenSharding/shardingsphere-spi-impl#55]
before commit this issue, I understand there must be some stratagy to check compile or dependecis or something like that by travis . however , I do got confused by some compiled erorr, please give me a hand cherry @cherrylzhao

1. I deployed the ss dependencies by following command in ss dev branch

```
mvn clean install -Dmaven.test.skip -Prelease
```

2. I try to compile spi-impl by following command 
```
mvn clean install -Dmaven.test.skip -U
```
3. and I got some compiled errors  

![Jietu20190809-error](https://user-images.githubusercontent.com/4112856/62753266-71991380-ba9d-11e9-9c06-bb1e149a354e.jpg)

for example , SQLRevertExecutorContext.java in spi-impl, one variable  

![Jietu20190809-spi-impl](https://user-images.githubusercontent.com/4112856/62753108-b07a9980-ba9c-11e9-9284-53cc5a52e676.jpg)

the path for OptimizedStatement is org.apache.shardingsphere.core.optimize.statement.OptimizedStatement

but in ss , the packge path for OptimizedStatement is org.apache.shardingsphere.core.optimize.api.statement

![Jietu20190809-ss](https://user-images.githubusercontent.com/4112856/62753183-02bbba80-ba9d-11e9-8f12-060e7b495510.jpg)

BTW , the version of both project is 4.0.0-RC2-SNAPSHOT .

**Comment by cherrylzhao** [comment]
ShardingSphere dev branch have adjust some APIs, and SPI branch should synchronize with it.
I'll fix the error later.

**Comment by taojintianxia** [comment]
I see . thx cherry

**Comment by cherrylzhao** [comment]
sorry for late response, I have fixed the error. you can try it again.

**Comment by taojintianxia** [comment]
it works
